### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by clement360** [bprodoehl/docker-turnserver#1]
Hello, I'm deploying the turnserver in a docker container. I need a username and password to pass into my webRTC app:

```
rtc.SERVER = {
    iceServers:[
      {url: "turn:", username:"", credential:""}
    ]
};
```

What are the default credentials? Also how can we change the credentials?

**Comment by clement360** [comment]
One more question: Will the turn server work if I use -p 443 and -p 22 instead of 3478?

**Comment by sojharo** [comment]
I also have the same question. Whenever we run this docker image, how can we specify the credentials?

**Comment by clement360** [comment]
It's been a long time since I used this, it was all set in some config file. I'd read the docs on the turn server repo this image is based on for more info. Although I think I ended up using an aws image instead of this docker image.
